# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerpeso', '0022_auto_20160512_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
