# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 21:06
from __future__ import unicode_literals

from django.db import migrations

def blank_to_email(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Agency = apps.get_model("primerpeso", "Agency")
    for agency in Agency.objects.all():
        if agency.email == '':
            agency.email = 'change@me.now'
            agency.save()


class Migration(migrations.Migration):

    dependencies = [
        ('primerpeso', '0023_auto_20160719_2105'),
    ]

    operations = [
        migrations.RunPython(blank_to_email),
    ]
